[2018-03-12 16:32:12] php.DEBUG: Warning: unlink(C:\xampp\htdocs\pf\var\cache\de~): No such file or directory {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\xampp\\\\htdocs\\\\pf\\\\vendor\\\\symfony\\\\filesystem\\\\Filesystem.php\",\"line\":184,\"trace\":[{\"file\":\"C:\\\\xampp\\\\htdocs\\\\pf\\\\vendor\\\\symfony\\\\framework-bundle\\\\Command\\\\CacheClearCommand.php\",\"line\":84,\"function\":\"remove\",\"class\":\"Symfony\\\\Component\\\\Filesystem\\\\Filesystem\",\"type\":\"->\"}],\"count\":1})"} []
[2018-03-12 16:32:12] php.DEBUG: Warning: unlink(C:\xampp\htdocs\pf\var\cache\de_): No such file or directory [] []
[2018-03-12 16:32:13] php.DEBUG: Warning: include(C:\xampp\htdocs\pf\var\cache\de_/srcDevDebugProjectContainer.php): failed to open stream: No such file or directory {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\xampp\\\\htdocs\\\\pf\\\\vendor\\\\symfony\\\\http-kernel\\\\Kernel.php\",\"line\":526,\"trace\":[{\"file\":\"C:\\\\xampp\\\\htdocs\\\\pf\\\\vendor\\\\symfony\\\\http-kernel\\\\Kernel.php\",\"line\":526,\"function\":\"include\"},{\"file\":\"C:\\\\xampp\\\\htdocs\\\\pf\\\\vendor\\\\symfony\\\\http-kernel\\\\Kernel.php\",\"line\":125,\"function\":\"initializeContainer\",\"class\":\"Symfony\\\\Component\\\\HttpKernel\\\\Kernel\",\"type\":\"->\"}],\"count\":1})"} []
[2018-03-12 16:32:13] php.DEBUG: Warning: include(): Failed opening 'C:\xampp\htdocs\pf\var\cache\de_/srcDevDebugProjectContainer.php' for inclusion (include_path='C:\xampp\php\PEAR') [] []
[2018-03-12 16:32:15] php.DEBUG: Warning: unlink(C:\xampp\htdocs\pf\var\cache\de_/ContainerTXg7lQB.legacy): No such file or directory {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\xampp\\\\htdocs\\\\pf\\\\vendor\\\\symfony\\\\http-kernel\\\\Kernel.php\",\"line\":707,\"trace\":[{\"file\":\"C:\\\\xampp\\\\htdocs\\\\pf\\\\vendor\\\\symfony\\\\http-kernel\\\\Kernel.php\",\"line\":535,\"function\":\"dumpContainer\",\"class\":\"Symfony\\\\Component\\\\HttpKernel\\\\Kernel\",\"type\":\"->\"}],\"count\":1})"} []
[2018-03-12 16:35:09] php.DEBUG: Warning: unlink(C:\xampp\htdocs\pf\var\cache\de~): No such file or directory {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\xampp\\\\htdocs\\\\pf\\\\vendor\\\\symfony\\\\filesystem\\\\Filesystem.php\",\"line\":184,\"trace\":[{\"file\":\"C:\\\\xampp\\\\htdocs\\\\pf\\\\vendor\\\\symfony\\\\framework-bundle\\\\Command\\\\CacheClearCommand.php\",\"line\":84,\"function\":\"remove\",\"class\":\"Symfony\\\\Component\\\\Filesystem\\\\Filesystem\",\"type\":\"->\"}],\"count\":1})"} []
[2018-03-12 16:35:09] php.DEBUG: Warning: unlink(C:\xampp\htdocs\pf\var\cache\de_): No such file or directory [] []
[2018-03-12 16:35:10] php.DEBUG: Warning: include(C:\xampp\htdocs\pf\var\cache\de_/srcDevDebugProjectContainer.php): failed to open stream: No such file or directory {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\xampp\\\\htdocs\\\\pf\\\\vendor\\\\symfony\\\\http-kernel\\\\Kernel.php\",\"line\":526,\"trace\":[{\"file\":\"C:\\\\xampp\\\\htdocs\\\\pf\\\\vendor\\\\symfony\\\\http-kernel\\\\Kernel.php\",\"line\":526,\"function\":\"include\"},{\"file\":\"C:\\\\xampp\\\\htdocs\\\\pf\\\\vendor\\\\symfony\\\\http-kernel\\\\Kernel.php\",\"line\":125,\"function\":\"initializeContainer\",\"class\":\"Symfony\\\\Component\\\\HttpKernel\\\\Kernel\",\"type\":\"->\"}],\"count\":1})"} []
[2018-03-12 16:35:10] php.DEBUG: Warning: include(): Failed opening 'C:\xampp\htdocs\pf\var\cache\de_/srcDevDebugProjectContainer.php' for inclusion (include_path='C:\xampp\php\PEAR') [] []
[2018-03-12 16:35:11] php.DEBUG: Warning: unlink(C:\xampp\htdocs\pf\var\cache\de_/Container9PBKku0.legacy): No such file or directory {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\xampp\\\\htdocs\\\\pf\\\\vendor\\\\symfony\\\\http-kernel\\\\Kernel.php\",\"line\":707,\"trace\":[{\"file\":\"C:\\\\xampp\\\\htdocs\\\\pf\\\\vendor\\\\symfony\\\\http-kernel\\\\Kernel.php\",\"line\":535,\"function\":\"dumpContainer\",\"class\":\"Symfony\\\\Component\\\\HttpKernel\\\\Kernel\",\"type\":\"->\"}],\"count\":1})"} []
[2018-03-12 17:43:12] php.DEBUG: Warning: fsockopen(): unable to connect to 127.0.0.1:8001 (Une tentative de connexion a échoué car le parti connecté n’a pas répondu convenablement au-delà d’une certaine durée ou une connexion établie a échoué car l’hôte de connexion n’a pas répondu. ) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\xampp\\\\htdocs\\\\pf\\\\vendor\\\\symfony\\\\web-server-bundle\\\\WebServerConfig.php\",\"line\":123,\"trace\":[{\"file\":\"C:\\\\xampp\\\\htdocs\\\\pf\\\\vendor\\\\symfony\\\\web-server-bundle\\\\WebServerConfig.php\",\"line\":54,\"function\":\"findBestPort\",\"class\":\"Symfony\\\\Bundle\\\\WebServerBundle\\\\WebServerConfig\",\"type\":\"->\"}],\"count\":1})"} []
[2018-03-12 17:49:16] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /"" at C:\xampp\htdocs\pf\vendor\symfony\http-kernel\EventListener\RouterListener.php line 144 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at C:\\xampp\\htdocs\\pf\\vendor\\symfony\\http-kernel\\EventListener\\RouterListener.php:144, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\xampp\\htdocs\\pf\\var\\cache\\dev\\srcDevDebugProjectContainerUrlMatcher.php:115)"} []
[2018-03-12 17:49:17] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"eb7fa9","_route":"_wdt"},"request_uri":"http://127.0.0.1:8001/_wdt/eb7fa9","method":"GET"} []
